// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxbwjbnqleepisdqzidj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4YndqYm5xbGVlcGlzZHF6aWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDA1MTksImV4cCI6MjA1OTk3NjUxOX0.mq5m-wIoXzdEZBLGmpZCMUeT61YE2OY46a2VU4RZcoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);